using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using UnityEngine.SceneManagement;

public class Monster1 : MonoBehaviour
{
    private void OnTriggerEnter2D(Collider2D collision)
    {
        var monster1 = GameObject.Find("BookOfDeath1").transform;

        var widthMonster = 0.75;
        var hero = GameObject.Find("Hero").transform;
        Hero.TakeDamage(widthMonster, monster1);




















        //var monster2 = GameObject.Find("BookOfDeath2").transform;
        //var monster3 = GameObject.Find("BookOfDeath3").transform;
        //if (Math.Abs(hero.position.x - monster2.position.x) <= widthMonster)
        //{
        //    Destroy(monster2.gameObject);
        //    livesHero -= 4;
        //}
        //if (Math.Abs(hero.position.x - monster3.position.x) <= widthMonster)
        //{
        //    Destroy(monster3.gameObject);
        //    livesHero -= 4;
        //}
    }
    //Transform monster1 = GameObject.Find("BookOfDeath1").transform;
    //Transform monster2 = GameObject.Find("BookOfDeath2").transform;
    //Transform monster3 = GameObject.Find("BookOfDeath3").transform;

    //private void OnTriggerEnter2D(Collider2D collision)
    //{
    //    //Destroy(hero.gameObject);   
    //    Debug.Log("���� ��� ���������!");
    //}
    //OnTriggerStay2D

    //private void OnTriggerExit2D(Collider2D collision)
    //{
    //    Debug.Log("Out to zone");
    //}
}
